"use server"

import { createClient } from "@/lib/supabase/server"

export interface Nominee {
  id: string
  category_id: string
  nominee_name: string
  nominee_description: string | null
  nominee_image_url: string | null
  unique_code: string
  votes_count: number
  created_at: string
  updated_at: string
  is_active: boolean
}

export interface NomineeWithCategory extends Nominee {
  category: {
    id: string
    category_name: string
  }
}

export interface CreateNomineeData {
  category_id: string
  nominee_name: string
  nominee_description?: string
  nominee_image_url?: string | null
}

export interface UpdateNomineeData {
  nominee_name?: string
  nominee_description?: string | null
  nominee_image_url?: string | null
  category_id?: string
}

export interface NomineeQueryParams {
  page?: number
  limit?: number
  search?: string
  categoryId?: string
}

export interface PaginatedNomineesResult {
  data: NomineeWithCategory[]
  total: number
  page: number
  limit: number
  totalPages: number
  hasNextPage: boolean
  hasPrevPage: boolean
}

const DEFAULT_PAGE_SIZE = 10

// Get nominees for an event with pagination, search, and category filter
export async function getEventNominees(
  eventId: string,
  params: NomineeQueryParams = {}
): Promise<PaginatedNomineesResult> {
  const supabase = await createClient()

  const { data: { user } } = await supabase.auth.getUser()
  if (!user) {
    throw new Error("Not authenticated")
  }

  const { page = 1, limit = DEFAULT_PAGE_SIZE, search, categoryId } = params
  const from = (page - 1) * limit
  const to = from + limit - 1

  // Build base query joining with categories
  let query = supabase
    .from("nominees")
    .select(
      `
      *,
      category:categories(id, category_name)
    `,
      { count: "exact" }
    )
    .eq("is_active", true)
    .eq("event_id", eventId)

  // Apply category filter
  if (categoryId) {
    query = query.eq("category_id", categoryId)
  }

  // Apply search filter (name or unique_code)
  if (search) {
    query = query.or(`nominee_name.ilike.%${search}%,unique_code.ilike.%${search}%`)
  }

  // Apply pagination
  query = query.range(from, to).order("created_at", { ascending: false })

  const { data, error, count } = await query

  if (error) {
    console.error("Error fetching nominees:", error)
    throw new Error("Failed to fetch nominees")
  }

  const total = count || 0
  const totalPages = Math.ceil(total / limit)

  // Transform data to ensure category is properly typed
  const nomineesWithCategory: NomineeWithCategory[] = (data || []).map((item) => ({
    ...(item as unknown as Nominee),
    category: Array.isArray(item.category) ? item.category[0] : item.category,
  }))

  return {
    data: nomineesWithCategory,
    total,
    page,
    limit,
    totalPages,
    hasNextPage: page < totalPages,
    hasPrevPage: page > 1,
  }
}

// Get categories for an event (for dropdown filter)
export async function getEventCategoriesForNominees(eventId: string) {
  const supabase = await createClient()

  const { data: { user } } = await supabase.auth.getUser()
  if (!user) {
    throw new Error("Not authenticated")
  }

  const { data, error } = await supabase
    .from("categories")
    .select("id, category_name")
    .eq("event_id", eventId)
    .eq("is_active", true)
    .order("category_name", { ascending: true })

  if (error) {
    console.error("Error fetching categories:", error)
    throw new Error("Failed to fetch categories")
  }

  return data || []
}

// Create a new nominee
export async function createNominee(data: CreateNomineeData): Promise<Nominee> {
  const supabase = await createClient()

  const { data: { user } } = await supabase.auth.getUser()
  if (!user) {
    throw new Error("Not authenticated")
  }

  // Verify user owns the category's event
  const { data: category, error: categoryError } = await supabase
    .from("categories")
    .select("event_id, events!inner(created_by)")
    .eq("id", data.category_id)
    .single()

  if (categoryError || !category) {
    throw new Error("Category not found")
  }

  // Insert nominee (unique_code auto-generated by trigger)
  const { data: nominee, error } = await supabase
    .from("nominees")
    .insert({
      category_id: data.category_id,
      nominee_name: data.nominee_name,
      nominee_description: data.nominee_description || null,
      nominee_image_url: data.nominee_image_url || null,
      created_by: user.id,
    })
    .select()
    .single()

  if (error) {
    console.error("Error creating nominee:", error)
    throw new Error("Failed to create nominee. " + error.message)
  }

  return nominee as Nominee
}

// Update a nominee
export async function updateNominee(
  nomineeId: string,
  data: UpdateNomineeData
): Promise<Nominee> {
  const supabase = await createClient()

  const { data: { user } } = await supabase.auth.getUser()
  if (!user) {
    throw new Error("Not authenticated")
  }

  const updateData: Record<string, unknown> = {
    updated_at: new Date().toISOString(),
  }

  if (data.nominee_name !== undefined) updateData.nominee_name = data.nominee_name
  if (data.nominee_description !== undefined) updateData.nominee_description = data.nominee_description
  if (data.nominee_image_url !== undefined) updateData.nominee_image_url = data.nominee_image_url
  if (data.category_id !== undefined) updateData.category_id = data.category_id

  const { data: nominee, error } = await supabase
    .from("nominees")
    .update(updateData)
    .eq("id", nomineeId)
    .select()
    .single()

  if (error) {
    console.error("Error updating nominee:", error)
    throw new Error("Failed to update nominee. " + error.message)
  }

  return nominee as Nominee
}

// Delete (soft delete) a nominee
export async function deleteNominee(nomineeId: string): Promise<void> {
  const supabase = await createClient()

  const { data: { user } } = await supabase.auth.getUser()
  if (!user) {
    throw new Error("Not authenticated")
  }

  const { error } = await supabase
    .from("nominees")
    .update({
      is_active: false,
      updated_at: new Date().toISOString(),
    })
    .eq("id", nomineeId)

  if (error) {
    console.error("Error deleting nominee:", error)
    throw new Error("Failed to delete nominee. " + error.message)
  }
}

// Upload nominee image
export async function uploadNomineeImage(file: File): Promise<string> {
  const supabase = await createClient()

  const { data: { user } } = await supabase.auth.getUser()
  if (!user) {
    throw new Error("Not authenticated")
  }

  const fileExt = file.name.split(".").pop()
  const fileName = `${user.id}/${Date.now()}.${fileExt}`
  const filePath = `${fileName}`

  const { error: uploadError } = await supabase.storage
    .from("nominee-images")
    .upload(filePath, file, {
      cacheControl: "3600",
      upsert: false,
    })

  if (uploadError) {
    console.error("Error uploading image:", uploadError)
    throw new Error("Failed to upload image. " + uploadError.message)
  }

  const { data: { publicUrl } } = supabase.storage.from("nominee-images").getPublicUrl(filePath)

  return publicUrl
}

// Get single nominee by ID
export async function getNomineeById(nomineeId: string): Promise<NomineeWithCategory> {
  const supabase = await createClient()

  const { data: { user } } = await supabase.auth.getUser()
  if (!user) {
    throw new Error("Not authenticated")
  }

  const { data, error } = await supabase
    .from("nominees")
    .select(
      `
      *,
      category:categories(id, category_name)
    `
    )
    .eq("id", nomineeId)
    .eq("is_active", true)
    .single()

  if (error) {
    console.error("Error fetching nominee:", error)
    throw new Error("Failed to fetch nominee")
  }

  return {
    ...(data as unknown as Nominee),
    category: Array.isArray(data.category) ? data.category[0] : data.category,
  }
}
